const schema = {
  version: "1.0.0",
  kind: "ARC#Config",
  groups: [
    {
      name: "View",
      description: "Settings related to the application look and feel",
      enabled: true,
      key: "view",
      kind: "ARC#ConfigGroup",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "List type",
          description: "The variant of most list items in the UI",
          key: "view.listType",
          default: "default",
          enum: ["default", "comfortable", "compact"],
          type: "string",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Popup menu",
          description: "Enables detachable application menu",
          key: "view.popupMenu",
          default: true,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Drag and drop",
          description: "Enables drag and drop in the application.",
          key: "view.draggableEnabled",
          default: true,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Font size",
          description: "The font size used by the application. In pixels.",
          key: "view.fontSize",
          default: 15,
          type: "number",
          suffix: "px",
        },
      ],
    },
    {
      name: "Request",
      description: "Settings related to the request processing",
      enabled: true,
      kind: "ARC#ConfigGroup",
      key: "request",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Request timeout",
          description: "The default timeout for a request. In seconds.",
          key: "request.timeout",
          suffix: "sec",
          default: 90,
          type: "number",
        },
        {
          kind: "ARC#ConfigGroup",
          enabled: true,
          name: "Variables",
          description: "Environments and variables global configuration.",
          key: "request.variables",
          layout: 'input-group',
          items: [
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Enable system variables",
              description: "Allow using system variables.",
              key: "request.useSystemVariables",
              default: true,
              type: "boolean",
            },
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Enable application variables",
              description: "Allow using application defined variables.",
              key: "request.useAppVariables",
              default: true,
              type: "boolean",
            },
          ]
        },
        {
          kind: "ARC#ConfigGroup",
          enabled: true,
          name: "Default behavior",
          description: "Configuration related to requests default behavior.",
          key: "request.behavior",
          layout: 'input-group',
          items: [
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Follow redirects",
              description: "Enables request redirection.",
              key: "request.followRedirects",
              default: true,
              type: "boolean",
            },
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Ignore content-* headers for GET",
              description:
                "Automatically removes content-* headers from the request for GET operation.",
              key: "request.ignoreContentOnGet",
              default: true,
              type: "boolean",
            },
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Default headers",
              description: 'Adds "user-agent" and "accept" headers when missing.',
              key: "request.defaultHeaders",
              default: false,
              type: "boolean",
            },
          ]
        },
        {
          kind: "ARC#ConfigGroup",
          enabled: true,
          name: "Session and security",
          description: "Configuration related to session management and security setting.",
          key: "request.security",
          layout: 'input-group',
          items: [
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Disable cookies",
              description: "When set it does not process cookies with the request.",
              key: "request.ignoreSessionCookies",
              default: false,
              type: "boolean",
            },
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Validate certificates",
              description: "Validate certificates when making a connection.",
              key: "request.validateCertificates",
              default: false,
              type: "boolean",
            },
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "OAuth 2 redirect URI",
              description: "The default OAuth 2 redirect URI.",
              key: "request.oauth2redirectUri",
              type: "string",
              default: "https://auth.advancedrestclient.com/oauth-popup.html",
            },
          ],
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Use Node.JS request engine",
          description: "Uses Node.JS HTTP engine instead of ARC's.",
          key: "request.nativeTransport",
          default: false,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Read OS' hosts file",
          description: "Passes the operating system's hosts list to the request engine.",
          key: "request.readOsHosts",
          type: "boolean",
          default: false,
        },
      ],
    },
    {
      name: "Proxy",
      description: "Application and request proxy configuration",
      enabled: true,
      key: "proxy",
      kind: "ARC#ConfigGroup",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Proxy settings enabled",
          description: "Enables or disables proxy settings.",
          key: "proxy.enabled",
          default: false,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Proxy URL",
          description: "The IP or URL of the proxy to use.",
          key: "proxy.url",
          type: "string",
        },
        {
          kind: "ARC#ConfigGroup",
          enabled: true,
          name: "Proxy authentication",
          description: "Configuration options for proxy authentication.",
          key: "proxy.authentication",
          layout: 'input-group',
          items: [
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Proxy username",
              description: "Optional proxy username.",
              key: "proxy.username",
              type: "string",
              topLevel: true,
            },
            {
              kind: "ARC#ConfigItem",
              enabled: true,
              name: "Proxy password",
              description: "Optional proxy password.",
              key: "proxy.password",
              type: "password",
              topLevel: true,
            },
          ],
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Apply to all application",
          description: "Applies the settings to the entire application, including updates and analytics.",
          key: "proxy.applyToApp",
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Detect and use system settings",
          description: "On supported platforms it detects system proxy settings and applies them to the application.",
          key: "proxy.useSystemSettings",
          type: "boolean",
        },
      ],
    },
    {
      name: "Privacy",
      description: "Settings related to your privacy",
      enabled: true,
      key: "privacy",
      kind: "ARC#ConfigGroup",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Telemetry",
          description: "Enable limited and anonymous usage statistics.",
          key: "privacy.telemetry",
          default: true,
          type: "boolean",
        },
        {
          kind: "ARC#LinkItem",
          enabled: true,
          name: "Privacy statement",
          target: "https://docs.google.com/document/d/1BzrKQ0NxFXuDIe2zMA-0SZBNU0P46MHr4GftZmoLUQU/edit",
        },
      ],
    },
    {
      name: "History",
      description: "Settings related to the history data storage",
      enabled: true,
      key: "history",
      kind: "ARC#ConfigGroup",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Enabled",
          description: "Enable history recording.",
          key: "history.enabled",
          default: true,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Fast search",
          description: "Use faster but less accurate search.",
          key: "history.fastSearch",
          default: true,
          type: "boolean",
        },
      ],
    },
    {
      name: "Request editor",
      description: "Specialized setting for the request editor",
      enabled: true,
      key: "requestEditor",
      kind: "ARC#ConfigGroup",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Auto encode",
          description: "Automatically encodes and decodes values in the www-url-form-encoded body editor.",
          key: "requestEditor.autoEncode",
          default: false,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Render the send and abort buttons",
          description: "Whether to render the send button in the request editor.",
          key: "requestEditor.sendButton",
          default: true,
          type: "boolean",
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Render transport status when sending the request",
          description: "Whether to render the request progress status in the request panel.",
          key: "requestEditor.progressInfo",
          default: true,
          type: "boolean",
        },
      ],
    },
    {
      name: "Response",
      description: "Settings related to the response rendering",
      enabled: true,
      key: "response",
      kind: "ARC#ConfigGroup",
      items: [
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Force raw view size limit",
          description: "A limit after which the response is not highlighted.",
          key: "response.forceRawSize",
          default: 4096,
          type: "number",
          suffix: 'KB',
        },
        {
          kind: "ARC#ConfigItem",
          enabled: true,
          name: "Response size warning limit",
          description: "When to show a response size warning before rendering.",
          key: "response.warningResponseMaxSize",
          default: 2048,
          type: "number",
          suffix: 'KB',
        },
      ],
    }
  ],
};
Object.freeze(schema);
Object.freeze(schema.groups);
export default schema;
